### ISSUE TITLE
won't build

### ISSUE THREAD

**Issue by dreamserpent** [Roughsketch/libdiscord#1] opened 2017-08-21 02:26 UTC
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2653	'verify_level': is not a class or namespace name	libdiscord	c:\libdiscord-master\libdiscord\src\guild.cpp	70	
Error	C2653	'notify_level': is not a class or namespace name	libdiscord	c:\libdiscord-master\libdiscord\src\guild.cpp	71

**Comment by Roughsketch** [comment] 2017-08-21 02:43
What are you building with? I can't reproduce it.

**Comment by dreamserpent** [comment] 2017-08-21 04:04
Visual Studio Community 2017. the 2 nugets required are installed as well, but the first one, CPPRestSDK was already installed when I looked.

both are on verify_level::None and notify_level::None - is this notation other than referencing a namespace?

**Comment by Roughsketch** [comment] 2017-08-21 04:21
I've found the issue. I changed the names at some point, but they may not have been pushed along with other changes. Should be fixed by the latest commit.

**Closed as completed** 2017-08-21 20:03 UTC
